-- AlterTable
ALTER TABLE "AIUsageLog" ADD COLUMN     "cost" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Subscription" ALTER COLUMN "orderId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "totalCostUSD" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalTokensUsed" INTEGER NOT NULL DEFAULT 0;
